package com.ecoresolve.service;
import com.ecoresolve.dto.ComplaintDtos.*; import com.ecoresolve.enums.*; import org.springframework.stereotype.Service; import java.util.*;
@Service public class AIService {
 public AIResult analyze(String text){String t=text.toLowerCase(Locale.ROOT); ComplaintCategory c=ComplaintCategory.OTHER; String sub="General Sustainability Issue"; Priority p=Priority.MEDIUM; String rec="Review the reported issue and take an appropriate corrective action.";
  if(t.matches(".*(tap|leak|water|faucet|pipe|toilet|overflow).*")){c=ComplaintCategory.WATER;sub="Water Leakage / Wastage";p=Priority.HIGH;rec="Inspect the affected fixture or plumbing and repair the leak to reduce water wastage.";}
  else if(t.matches(".*(light|electric|electricity|fan|ac|air conditioner|power|energy).*")){c=ComplaintCategory.ENERGY;sub="Energy Consumption";p=Priority.MEDIUM;rec="Inspect the electrical equipment and reduce unnecessary energy consumption.";}
  else if(t.matches(".*(garbage|waste|bin|litter|plastic|trash|recycl).*")){c=ComplaintCategory.WASTE;sub="Waste Management";p=Priority.MEDIUM;rec="Check waste-bin capacity, segregation and collection frequency in the reported area.";}
  else if(t.matches(".*(tree|garden|air pollution|smoke|drain|road|campus|environment).*")){c=ComplaintCategory.INFRASTRUCTURE_ENVIRONMENT;sub="Environmental / Infrastructure Issue";p=Priority.MEDIUM;rec="Inspect the reported area and assign the issue to the responsible maintenance team.";}
  String summary="A sustainability-related issue was reported: "+(text.length()>180?text.substring(0,180)+"...":text); return new AIResult(c,sub,p,summary,rec,"EcoResolve-RuleBased-MVP"); }
 public InsightResponse insights(List<String> complaints){long water=complaints.stream().filter(x->analyze(x).category()==ComplaintCategory.WATER).count(); long energy=complaints.stream().filter(x->analyze(x).category()==ComplaintCategory.ENERGY).count(); long waste=complaints.stream().filter(x->analyze(x).category()==ComplaintCategory.WASTE).count(); List<Insight> out=new ArrayList<>(); if(water>0)out.add(new Insight("Water issues","Water-related complaints detected: "+water,"Inspect frequently reported water fixtures and plumbing areas.")); if(energy>0)out.add(new Insight("Energy issues","Energy-related complaints detected: "+energy,"Review lighting, fans and electrical usage in frequently reported areas.")); if(waste>0)out.add(new Insight("Waste pattern","Waste-related complaints detected: "+waste,"Review waste-bin placement, segregation and collection frequency.")); if(out.isEmpty())out.add(new Insight("No dominant pattern","Not enough categorized complaints for a meaningful hotspot insight yet.","Collect more complaint data and regenerate the analysis.")); return new InsightResponse(out,java.time.LocalDateTime.now());}
}
