package com.ecoresolve.service;
import com.ecoresolve.dto.ComplaintDtos.*; import com.ecoresolve.entity.*; import com.ecoresolve.enums.*; import com.ecoresolve.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class ComplaintService {
 private final ComplaintRepository complaints; private final LocationRepository locations; private final AIAnalysisRepository analyses; private final ComplaintHistoryRepository history; private final UserRepository users; private final AIService ai;
 private User current(String email){return users.findByEmail(email).orElseThrow();}
 @Transactional public ComplaintView create(String email,CreateComplaintRequest r){User u=current(email); Location l=locations.findById(r.locationId()).orElseThrow(()->new NoSuchElementException("Location not found")); Complaint c=new Complaint();c.setUser(u);c.setLocation(l);c.setDescription(r.description().trim());c.setImageUrl(r.imageUrl());c.setStatus(ComplaintStatus.PENDING);var result=ai.analyze(c.getDescription());applyAI(c,result);c=complaints.save(c);AIAnalysis a=new AIAnalysis();a.setComplaint(c);a.setModel(result.model());a.setCategory(result.category());a.setSubcategory(result.subcategory());a.setPriority(result.priority());a.setSummary(result.summary());a.setRecommendation(result.recommendation());analyses.save(a);addHistory(c,null,ComplaintStatus.PENDING,u,"Complaint submitted and AI analysis generated");return view(c,List.of(historyViewForSubmission(u)));}
 private ComplaintHistory historyViewForSubmission(User u){ComplaintHistory h=new ComplaintHistory();h.setChangedBy(u);h.setOldStatus(null);h.setNewStatus(ComplaintStatus.PENDING);h.setNote("Complaint submitted");h.setCreatedAt(LocalDateTime.now());return h;}
 private void applyAI(Complaint c,AIResult r){c.setAiCategory(r.category());c.setAiSubcategory(r.subcategory());c.setAiPriority(r.priority());c.setFinalCategory(r.category());c.setFinalPriority(r.priority());c.setAiSummary(r.summary());c.setAiRecommendation(r.recommendation());}
 @Transactional(readOnly=true) public Page<ComplaintView> mine(String email,Pageable p){User u=current(email);return complaints.findByUserId(u.getId(),p).map(c->view(c,history.findByComplaintIdOrderByCreatedAtAsc(c.getId())));}
 @Transactional(readOnly=true) public ComplaintView getMine(String email,Long id){Complaint c=get(id);if(!c.getUser().getEmail().equals(email))throw new org.springframework.security.access.AccessDeniedException("Not your complaint");return view(c,history.findByComplaintIdOrderByCreatedAtAsc(id));}
 @Transactional(readOnly=true) public Page<ComplaintView> all(Pageable p){return complaints.findAll(p).map(c->view(c,history.findByComplaintIdOrderByCreatedAtAsc(c.getId())));}
 @Transactional public ComplaintView update(Long id,AdminUpdateRequest r,String email){Complaint c=get(id);ComplaintStatus old=c.getStatus();if(r.category()!=null)c.setFinalCategory(r.category());if(r.priority()!=null)c.setFinalPriority(r.priority());if(r.status()!=null)c.setStatus(r.status());if(r.resolutionNote()!=null)c.setResolutionNote(r.resolutionNote());if(c.getStatus()==ComplaintStatus.RESOLVED&&c.getResolvedAt()==null)c.setResolvedAt(LocalDateTime.now());if(c.getStatus()!=ComplaintStatus.RESOLVED)c.setResolvedAt(null);c=complaints.save(c);if(r.status()!=null&&r.status()!=old)addHistory(c,old,r.status(),current(email),r.resolutionNote());return view(c,history.findByComplaintIdOrderByCreatedAtAsc(id));}
 private Complaint get(Long id){return complaints.findById(id).orElseThrow(()->new NoSuchElementException("Complaint not found"));}
 private void addHistory(Complaint c,ComplaintStatus old,ComplaintStatus next,User by,String note){ComplaintHistory h=new ComplaintHistory();h.setComplaint(c);h.setChangedBy(by);h.setOldStatus(old);h.setNewStatus(next);h.setNote(note);history.save(h);}
 private ComplaintView view(Complaint c,List<ComplaintHistory> hs){List<HistoryView> hv=hs.stream().map(h->new HistoryView(h.getOldStatus(),h.getNewStatus(),h.getChangedBy()==null?"System":h.getChangedBy().getName(),h.getNote(),h.getCreatedAt())).toList();return new ComplaintView(c.getId(),c.getDescription(),c.getLocation().getName(),c.getAiCategory(),c.getAiSubcategory(),c.getAiPriority(),c.getFinalCategory(),c.getFinalPriority(),c.getAiSummary(),c.getAiRecommendation(),c.getStatus(),c.getResolutionNote(),c.getCreatedAt(),c.getUpdatedAt(),c.getResolvedAt(),hv);}
 public ComplaintView adminGet(Long id){Complaint c=get(id);return view(c,history.findByComplaintIdOrderByCreatedAtAsc(id));}
 public DashboardStats dashboard(){return new DashboardStats(complaints.count(),complaints.countByStatus(ComplaintStatus.PENDING),complaints.countByStatus(ComplaintStatus.IN_PROGRESS),complaints.countByStatus(ComplaintStatus.RESOLVED),complaints.countByFinalPriority(Priority.HIGH));}
 public Analytics analytics(){Map<String,Long> cat=new LinkedHashMap<>(), pri=new LinkedHashMap<>(), stat=new LinkedHashMap<>(); for(var c:ComplaintCategory.values())cat.put(c.name(),complaints.findAll().stream().filter(x->(x.getFinalCategory()!=null?x.getFinalCategory():x.getAiCategory())==c).count()); for(var p:Priority.values())pri.put(p.name(),complaints.findAll().stream().filter(x->(x.getFinalPriority()!=null?x.getFinalPriority():x.getAiPriority())==p).count()); for(var s:ComplaintStatus.values())stat.put(s.name(),complaints.countByStatus(s)); return new Analytics(cat,pri,stat);}
 public InsightResponse insights(){return ai.insights(complaints.findAll().stream().map(Complaint::getDescription).toList());}
}
